<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.13">
  <compounddef id="classQgsCsException" kind="class" language="C++" prot="public">
    <compoundname>QgsCsException</compoundname>
    <basecompoundref refid="classQgsException" prot="public" virt="non-virtual">QgsException</basecompoundref>
    <includes refid="qgsexception_8h" local="no">qgsexception.h</includes>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classQgsCsException_1a950da27154640c09f9ba8d0637d7ca89" prot="public" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type></type>
        <definition>QgsCsException::QgsCsException</definition>
        <argsstring>(const QString &amp;message)</argsstring>
        <name>QgsCsException</name>
        <param>
          <type>const QString &amp;</type>
          <declname>message</declname>
        </param>
        <briefdescription>
<para>Constructor for <ref refid="classQgsCsException" kindref="compound">QgsCsException</ref>, with the specified error <emphasis>message</emphasis>. </para>        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" line="72" column="1" bodyfile="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" bodystart="72" bodyend="72"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
<para>Custom exception class for Coordinate Reference System related exceptions. </para>    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="2080">
        <label>QgsCsException</label>
        <link refid="classQgsCsException"/>
        <childnode refid="2081" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2081">
        <label>QgsException</label>
        <link refid="classQgsException"/>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="2082">
        <label>QgsCsException</label>
        <link refid="classQgsCsException"/>
        <childnode refid="2083" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2083">
        <label>QgsException</label>
        <link refid="classQgsException"/>
      </node>
    </collaborationgraph>
    <location file="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" line="66" column="1" bodyfile="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" bodystart="65" bodyend="74"/>
    <listofallmembers>
      <member refid="classQgsCsException_1a950da27154640c09f9ba8d0637d7ca89" prot="public" virt="non-virtual"><scope>QgsCsException</scope><name>QgsCsException</name></member>
      <member refid="classQgsException_1ad8b305f8803fb08aecd0ab3a9f73dde3" prot="public" virt="non-virtual"><scope>QgsCsException</scope><name>QgsException</name></member>
      <member refid="classQgsException_1aae00b1a7dfb1f6b6f9e399365715a2b4" prot="public" virt="non-virtual"><scope>QgsCsException</scope><name>what</name></member>
      <member refid="classQgsException_1a56151d55ee0b611b03c416ec7c7f06db" prot="public" virt="virtual"><scope>QgsCsException</scope><name>~QgsException</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
