<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.13">
  <compounddef id="classQgsProcessingException" kind="class" language="C++" prot="public">
    <compoundname>QgsProcessingException</compoundname>
    <basecompoundref refid="classQgsException" prot="public" virt="non-virtual">QgsException</basecompoundref>
    <includes refid="qgsexception_8h" local="no">qgsexception.h</includes>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classQgsProcessingException_1ad1b6f6d5dd7590f5847ea7ae10bedaca" prot="public" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type></type>
        <definition>QgsProcessingException::QgsProcessingException</definition>
        <argsstring>(const QString &amp;message)</argsstring>
        <name>QgsProcessingException</name>
        <param>
          <type>const QString &amp;</type>
          <declname>message</declname>
        </param>
        <briefdescription>
<para>Constructor for <ref refid="classQgsProcessingException" kindref="compound">QgsProcessingException</ref>, with the specified error <emphasis>message</emphasis>. </para>        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" line="89" column="1" bodyfile="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" bodystart="89" bodyend="89"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
<para>Custom exception class for processing related exceptions. </para>    </briefdescription>
    <detaileddescription>
<para><simplesect kind="since"><para>QGIS 3.0 </para></simplesect>
</para>    </detaileddescription>
    <inheritancegraph>
      <node id="6768">
        <label>QgsException</label>
        <link refid="classQgsException"/>
      </node>
      <node id="6767">
        <label>QgsProcessingException</label>
        <link refid="classQgsProcessingException"/>
        <childnode refid="6768" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="6770">
        <label>QgsException</label>
        <link refid="classQgsException"/>
      </node>
      <node id="6769">
        <label>QgsProcessingException</label>
        <link refid="classQgsProcessingException"/>
        <childnode refid="6770" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" line="83" column="1" bodyfile="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" bodystart="82" bodyend="91"/>
    <listofallmembers>
      <member refid="classQgsException_1ad8b305f8803fb08aecd0ab3a9f73dde3" prot="public" virt="non-virtual"><scope>QgsProcessingException</scope><name>QgsException</name></member>
      <member refid="classQgsProcessingException_1ad1b6f6d5dd7590f5847ea7ae10bedaca" prot="public" virt="non-virtual"><scope>QgsProcessingException</scope><name>QgsProcessingException</name></member>
      <member refid="classQgsException_1aae00b1a7dfb1f6b6f9e399365715a2b4" prot="public" virt="non-virtual"><scope>QgsProcessingException</scope><name>what</name></member>
      <member refid="classQgsException_1a56151d55ee0b611b03c416ec7c7f06db" prot="public" virt="virtual"><scope>QgsProcessingException</scope><name>~QgsException</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
