<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.13">
  <compounddef id="classQgsException" kind="class" language="C++" prot="public">
    <compoundname>QgsException</compoundname>
    <derivedcompoundref refid="classQgsCsException" prot="public" virt="non-virtual">QgsCsException</derivedcompoundref>
    <derivedcompoundref refid="classQgsProcessingException" prot="public" virt="non-virtual">QgsProcessingException</derivedcompoundref>
    <derivedcompoundref refid="classQgsWkbException" prot="public" virt="non-virtual">QgsWkbException</derivedcompoundref>
    <includes refid="qgsexception_8h" local="no">qgsexception.h</includes>
      <sectiondef kind="private-attrib">
      <memberdef kind="variable" id="classQgsException_1ae446b5f708ae24681079d89e5a0ee827" prot="private" static="no" mutable="no">
        <type>QString</type>
        <definition>QString QgsException::mWhat</definition>
        <argsstring></argsstring>
        <name>mWhat</name>
        <briefdescription>
<para>Description of exception. </para>        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" line="56" column="1" bodyfile="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" bodystart="56" bodyend="-1"/>
      </memberdef>
      </sectiondef>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classQgsException_1ad8b305f8803fb08aecd0ab3a9f73dde3" prot="public" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type></type>
        <definition>QgsException::QgsException</definition>
        <argsstring>(const QString &amp;message)</argsstring>
        <name>QgsException</name>
        <param>
          <type>const QString &amp;</type>
          <declname>message</declname>
        </param>
        <briefdescription>
<para>Constructor for <ref refid="classQgsException" kindref="compound">QgsException</ref>, with the specified error <emphasis>message</emphasis>. </para>        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" line="41" column="1" bodyfile="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" bodystart="41" bodyend="43"/>
      </memberdef>
      <memberdef kind="function" id="classQgsException_1a56151d55ee0b611b03c416ec7c7f06db" prot="public" static="no" const="no" explicit="no" inline="no" virt="virtual">
        <type></type>
        <definition>virtual QgsException::~QgsException</definition>
        <argsstring>()=default</argsstring>
        <name>~QgsException</name>
        <exceptions> throw ()</exceptions>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" line="45" column="1"/>
      </memberdef>
      <memberdef kind="function" id="classQgsException_1aae00b1a7dfb1f6b6f9e399365715a2b4" prot="public" static="no" const="yes" explicit="no" inline="yes" virt="non-virtual">
        <type>QString</type>
        <definition>QString QgsException::what</definition>
        <argsstring>() const</argsstring>
        <name>what</name>
        <exceptions> throw ()</exceptions>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><simplesect kind="note"><para>not available in Python bindings </para></simplesect>
</para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" line="48" column="1" bodyfile="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" bodystart="48" bodyend="51"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
<para>Defines a QGIS exception class. </para>    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="2743">
        <label>QgsCsException</label>
        <link refid="classQgsCsException"/>
        <childnode refid="2742" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2745">
        <label>QgsWkbException</label>
        <link refid="classQgsWkbException"/>
        <childnode refid="2742" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2742">
        <label>QgsException</label>
        <link refid="classQgsException"/>
      </node>
      <node id="2744">
        <label>QgsProcessingException</label>
        <link refid="classQgsProcessingException"/>
        <childnode refid="2742" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <location file="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" line="35" column="1" bodyfile="/home/suricactus/work/qgis/QGIS/src/core/qgsexception.h" bodystart="34" bodyend="58"/>
    <listofallmembers>
      <member refid="classQgsException_1ae446b5f708ae24681079d89e5a0ee827" prot="private" virt="non-virtual"><scope>QgsException</scope><name>mWhat</name></member>
      <member refid="classQgsException_1ad8b305f8803fb08aecd0ab3a9f73dde3" prot="public" virt="non-virtual"><scope>QgsException</scope><name>QgsException</name></member>
      <member refid="classQgsException_1aae00b1a7dfb1f6b6f9e399365715a2b4" prot="public" virt="non-virtual"><scope>QgsException</scope><name>what</name></member>
      <member refid="classQgsException_1a56151d55ee0b611b03c416ec7c7f06db" prot="public" virt="virtual"><scope>QgsException</scope><name>~QgsException</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
