<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.13">
  <compounddef id="classpal_1_1InternalException_1_1Empty" kind="class" language="C++" prot="public">
    <compoundname>pal::InternalException::Empty</compoundname>
    <basecompoundref prot="public" virt="non-virtual">exception</basecompoundref>
    <includes refid="internalexception_8h" local="no">internalexception.h</includes>
      <sectiondef kind="private-func">
      <memberdef kind="function" id="classpal_1_1InternalException_1_1Empty_1ad9e753ee167deddc585f26e220b5018f" prot="private" static="no" const="yes" explicit="no" inline="yes" virt="non-virtual">
        <type>const char *</type>
        <definition>const char* pal::InternalException::Empty::what</definition>
        <argsstring>() const override</argsstring>
        <name>what</name>
        <exceptions> throw ()</exceptions>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/suricactus/work/qgis/QGIS/src/core/pal/internalexception.h" line="64" column="1" bodyfile="/home/suricactus/work/qgis/QGIS/src/core/pal/internalexception.h" bodystart="64" bodyend="67"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
<para>Thrown when trying to access an empty data set. </para>    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="288">
        <label>exception</label>
      </node>
      <node id="287">
        <label>pal::InternalException::Empty</label>
        <link refid="classpal_1_1InternalException_1_1Empty"/>
        <childnode refid="288" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="290">
        <label>exception</label>
      </node>
      <node id="289">
        <label>pal::InternalException::Empty</label>
        <link refid="classpal_1_1InternalException_1_1Empty"/>
        <childnode refid="290" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="/home/suricactus/work/qgis/QGIS/src/core/pal/internalexception.h" line="63" column="1" bodyfile="/home/suricactus/work/qgis/QGIS/src/core/pal/internalexception.h" bodystart="62" bodyend="68"/>
    <listofallmembers>
      <member refid="classpal_1_1InternalException_1_1Empty_1ad9e753ee167deddc585f26e220b5018f" prot="private" virt="non-virtual"><scope>pal::InternalException::Empty</scope><name>what</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
