<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.13">
  <compounddef id="classpal_1_1InternalException_1_1UnknownGeometry" kind="class" language="C++" prot="public">
    <compoundname>pal::InternalException::UnknownGeometry</compoundname>
    <basecompoundref prot="public" virt="non-virtual">exception</basecompoundref>
    <includes refid="internalexception_8h" local="no">internalexception.h</includes>
      <sectiondef kind="private-func">
      <memberdef kind="function" id="classpal_1_1InternalException_1_1UnknownGeometry_1a9fccae352b5eac6e5d14ac80edf582f1" prot="private" static="no" const="yes" explicit="no" inline="yes" virt="non-virtual">
        <type>const char *</type>
        <definition>const char* pal::InternalException::UnknownGeometry::what</definition>
        <argsstring>() const override</argsstring>
        <name>what</name>
        <exceptions> throw ()</exceptions>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/suricactus/work/qgis/QGIS/src/core/pal/internalexception.h" line="88" column="1" bodyfile="/home/suricactus/work/qgis/QGIS/src/core/pal/internalexception.h" bodystart="88" bodyend="91"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
<para>Thrown when a geometry type is not like expected. </para>    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="10298">
        <label>exception</label>
      </node>
      <node id="10297">
        <label>pal::InternalException::UnknownGeometry</label>
        <link refid="classpal_1_1InternalException_1_1UnknownGeometry"/>
        <childnode refid="10298" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="10300">
        <label>exception</label>
      </node>
      <node id="10299">
        <label>pal::InternalException::UnknownGeometry</label>
        <link refid="classpal_1_1InternalException_1_1UnknownGeometry"/>
        <childnode refid="10300" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="/home/suricactus/work/qgis/QGIS/src/core/pal/internalexception.h" line="87" column="1" bodyfile="/home/suricactus/work/qgis/QGIS/src/core/pal/internalexception.h" bodystart="86" bodyend="92"/>
    <listofallmembers>
      <member refid="classpal_1_1InternalException_1_1UnknownGeometry_1a9fccae352b5eac6e5d14ac80edf582f1" prot="private" virt="non-virtual"><scope>pal::InternalException::UnknownGeometry</scope><name>what</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
